// data.jsx — listings, regions, types. Sourced from scraped property data
// (Capital '99 Balaton portfolio, used as demo tenant for the white-label mockup).

const PROPERTIES = [
  {
    id: "4385",
    title: "Family house in Vonyarcvashegy",
    location: "Vonyarcvashegy, Balaton",
    region: "Balaton",
    price: 189000,
    rooms: 4, baths: 2, area: 194, plot: 700,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 29,
    src: "uploads/scraped-properties/images/family-house-4385.jpg",
    lat: 46.7681, lng: 17.3197,
    description: "Constantly maintained detached house in Vonyarcvashegy, near the center of the town is for sale",
  },
  {
    id: "4384",
    title: "Farm estate near Nagykanizsa",
    location: "Nagykanizsa, West Transdanubia",
    region: "West Transdanubia",
    price: 72222,
    rooms: 2, baths: null, area: 42, plot: 8008,
    type: "Farmhouse",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-3",
    photoCount: 28,
    src: "uploads/scraped-properties/images/agricultural-4384.jpg",
    lat: 46.4592, lng: 16.9897,
    description: "Farm estate only few kms from Nagykanizsa is for sale",
  },
  {
    id: "4383",
    title: "Family house in Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 412500,
    rooms: 4, baths: 2, area: 110, plot: 475,
    type: "House",
    tag: "Refurbished",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 27,
    src: "uploads/scraped-properties/images/family-house-4383.jpg",
    lat: 46.8, lng: 17.3,
    description: "Detached house completely refurbished in 2025 located only 500 metres from the Lake Balaton is for sale",
  },
  {
    id: "4381",
    title: "Family house in Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 89000,
    rooms: 3, baths: null, area: 100, plot: 1141,
    type: "House",
    tag: "Refurbished",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 25,
    src: null,
    lat: 46.8, lng: 17.3,
    description: "Detached house refurbished in 2005 nicely located in a calm side street is for sale",
  },
  {
    id: "4380",
    title: "Family house in Hévíz",
    location: "Hévíz, Balaton",
    region: "Balaton",
    price: 380000,
    rooms: 5, baths: 2, area: 153, plot: 800,
    type: "House",
    tag: "Refurbished",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 24,
    src: "uploads/scraped-properties/images/family-house-4380.jpg",
    lat: 46.7878, lng: 17.1903,
    description: "Detached house located in the spa town Hévíz in valuable area refurbished in 2015 is for sale",
  },
  {
    id: "4378",
    title: "Family house in Cserszegtomaj",
    location: "Cserszegtomaj, Balaton",
    region: "Balaton",
    price: 208000,
    rooms: 5, baths: 2, area: 110, plot: 1500,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 22,
    src: null,
    lat: 46.7917, lng: 17.2333,
    description: "Modern, energy efficient house centrally located in Cserszegtomaj in a silent side street is for sale",
  },
  {
    id: "4377",
    title: "Family house in Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 275000,
    rooms: 7, baths: 2, area: 126, plot: 250,
    type: "House",
    tag: "City centre",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 21,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Detached house in calm town part of Keszthely is for sale",
  },
  {
    id: "4376",
    title: "Family house in Cserszegtomaj",
    location: "Cserszegtomaj, Balaton",
    region: "Balaton",
    price: 340000,
    rooms: 5, baths: 2, area: 164, plot: 800,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 20,
    src: null,
    lat: 46.7917, lng: 17.2333,
    description: "Modern, energy efficient house centrally located in Cserszegtomaj in a silent side street is for sale",
  },
  {
    id: "4375",
    title: "Family house in Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 441666,
    rooms: 6, baths: 2, area: 140, plot: 270,
    type: "House",
    tag: "City centre",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 19,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Terrace house in good condition located in Keszthely is for sale",
  },
  {
    id: "4374",
    title: "Family house in Balatonszentgyörgy",
    location: "Balatonszentgyörgy, Balaton",
    region: "Balaton",
    price: 148000,
    rooms: 4, baths: 2, area: 101, plot: 3505,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 18,
    src: null,
    lat: 46.6864, lng: 17.3236,
    description: "Detached house in a calm side street of Balatonszentgyörgy is for sale",
  },
  {
    id: "4372",
    title: "Building plot · Vonyarcvashegy",
    location: "Vonyarcvashegy, Balaton",
    region: "Balaton",
    price: 152777,
    rooms: null, baths: null, area: null, plot: 983,
    type: "Plot",
    tag: "Building land",
    agent: "Capital '99 Balaton",
    swatch: "swatch-6",
    photoCount: 16,
    src: "uploads/scraped-properties/images/building-site-4372.jpg",
    lat: 46.7681, lng: 17.3197,
    description: "Wide, square-shaped construction lot in Vonyarcvashegy for sale",
  },
  {
    id: "4371",
    title: "Building plot · Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 250000,
    rooms: null, baths: null, area: null, plot: 2062,
    type: "Plot",
    tag: "Panoramic view",
    agent: "Capital '99 Balaton",
    swatch: "swatch-6",
    photoCount: 15,
    src: "uploads/scraped-properties/images/building-site-4371.jpg",
    lat: 46.8, lng: 17.3,
    description: "Construction lot directly next to forest with panoramic view of the Lake Balaton is for sale",
  },
  {
    id: "4370",
    title: "Family house in Hévíz",
    location: "Hévíz, Balaton",
    region: "Balaton",
    price: 380000,
    rooms: 9, baths: 6, area: 313, plot: 500,
    type: "House",
    tag: "Near thermal spa",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 14,
    src: null,
    lat: 46.7878, lng: 17.1903,
    description: "In Hévíz, 10 walking minutes from the thermal lake house with 4 apartments is for sale",
  },
  {
    id: "4368",
    title: "Family house in Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 477777,
    rooms: 5, baths: 2, area: 242, plot: 533,
    type: "House",
    tag: "Refurbished",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 12,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Refurbished detached house fit for two generation in the eastern part of the town Keszthely is for sale",
  },
  {
    id: "4367",
    title: "Apartment · Hévíz",
    location: "Hévíz, Balaton",
    region: "Balaton",
    price: 346388,
    rooms: 3, baths: 2, area: 84, plot: null,
    type: "Apartment",
    tag: "Spa town",
    agent: "Capital '99 Balaton",
    swatch: "swatch-2",
    photoCount: 39,
    src: "uploads/scraped-properties/images/flat-4367.jpg",
    lat: 46.7878, lng: 17.1903,
    description: "Quality two-storey condominium in frequented, but also calm district of Hévíz is for sale",
  },
  {
    id: "4366",
    title: "Apartment · Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 127500,
    rooms: 2, baths: null, area: 54, plot: null,
    type: "Apartment",
    tag: "Walk to lake",
    agent: "Capital '99 Balaton",
    swatch: "swatch-2",
    photoCount: 38,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Apartment in the most valuable part of the town Keszthely, 5 walking minutes from the Lake Balaton is for sale",
  },
  {
    id: "4365",
    title: "Apartment · Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 130277,
    rooms: 2, baths: null, area: 45, plot: null,
    type: "Apartment",
    tag: "Walk to lake",
    agent: "Capital '99 Balaton",
    swatch: "swatch-2",
    photoCount: 37,
    src: "uploads/scraped-properties/images/flat-4365.jpg",
    lat: 46.7686, lng: 17.2444,
    description: "Apartment in the most valuable part of the town Keszthely, 5 walking minutes from the Lake Balaton is for sale",
  },
  {
    id: "4364",
    title: "Family house in Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 302777,
    rooms: 3, baths: null, area: 90, plot: 470,
    type: "House",
    tag: "Walk to lake",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 36,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Bourgeois house in most valuable part of Keszthely, 5 walking minutes from the Lake Balaton is for sale",
  },
  {
    id: "4362",
    title: "Family house in Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 1500000,
    rooms: 6, baths: 3, area: 283, plot: 820,
    type: "House",
    tag: "City centre",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 34,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Premium quality detached house built in 2021 located in Gyenesdiás, near Keszthely and Hévíz for sale",
  },
  {
    id: "4361",
    title: "Apartment · Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 200000,
    rooms: 4, baths: null, area: 70, plot: null,
    type: "Apartment",
    tag: "Refurbished",
    agent: "Capital '99 Balaton",
    swatch: "swatch-2",
    photoCount: 33,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Refurbished flat with 3 bedrooms and a sitting room and a balcony in favourite part of the town Keszthely is for sale",
  },
  {
    id: "4359",
    title: "Apartment · Vonyarcvashegy",
    location: "Vonyarcvashegy, Balaton",
    region: "Balaton",
    price: 169000,
    rooms: 3, baths: null, area: 62, plot: null,
    type: "Apartment",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-2",
    photoCount: 31,
    src: null,
    lat: 46.7681, lng: 17.3197,
    description: "Very nice ground floor flat as new in Vonyarcvashegy, in closed residential park",
  },
  {
    id: "4358",
    title: "Family house in Hévíz",
    location: "Hévíz, Balaton",
    region: "Balaton",
    price: 358333,
    rooms: 6, baths: 3, area: 210, plot: 2908,
    type: "House",
    tag: "Near thermal spa",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 30,
    src: null,
    lat: 46.7878, lng: 17.1903,
    description: "Constantly maintained detached house with two living units near the spa town of Hévíz, in a calm settlement",
  },
  {
    id: "4357",
    title: "Family house in Cserszegtomaj",
    location: "Cserszegtomaj, Balaton",
    region: "Balaton",
    price: 780000,
    rooms: 3, baths: null, area: 209, plot: 1943,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 29,
    src: null,
    lat: 46.7917, lng: 17.2333,
    description: "High-standard detached house built in very good quality in Cserszegtomaj",
  },
  {
    id: "4356",
    title: "Apartment · Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 165000,
    rooms: 5, baths: 2, area: 85, plot: 364,
    type: "Apartment",
    tag: "City centre",
    agent: "Capital '99 Balaton",
    swatch: "swatch-2",
    photoCount: 28,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Two apartments in good condition in the down town of Keszthely",
  },
  {
    id: "4355",
    title: "Family house in Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 1180555,
    rooms: 6, baths: 3, area: 325, plot: 2158,
    type: "House",
    tag: "City centre",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 27,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Stunningly located detached house near forest next to Keszthely and Hévíz",
  },
  {
    id: "4351",
    title: "Family house in Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 499000,
    rooms: 4, baths: 2, area: 220, plot: 780,
    type: "House",
    tag: "Refurbished",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 23,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Completely renovated villa in Keszthely",
  },
  {
    id: "4350",
    title: "Building plot · Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 83055,
    rooms: null, baths: null, area: null, plot: 247,
    type: "Plot",
    tag: "Building land",
    agent: "Capital '99 Balaton",
    swatch: "swatch-6",
    photoCount: 22,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Construction lot in the downtown of Keszthely is for sale",
  },
  {
    id: "4349",
    title: "Family house in Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 1611111,
    rooms: 5, baths: 5, area: 379, plot: 1750,
    type: "House",
    tag: "Panoramic view",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 21,
    src: null,
    lat: 46.8, lng: 17.3,
    description: "Detached house with unobstructed panoramic view of the Lake Balaton is for sale",
  },
  {
    id: "4345",
    title: "New-build house · Cserszegtomaj",
    location: "Cserszegtomaj, Balaton",
    region: "Balaton",
    price: 430000,
    rooms: 4, baths: null, area: 112, plot: 700,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 17,
    src: null,
    lat: 46.7917, lng: 17.2333,
    description: "Quality one-storey detached house in Cserszegtomaj is for sale",
  },
  {
    id: "4344",
    title: "New-build house · Cserszegtomaj",
    location: "Cserszegtomaj, Balaton",
    region: "Balaton",
    price: 495000,
    rooms: 4, baths: 2, area: 122, plot: 900,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 16,
    src: "uploads/scraped-properties/images/family-house-4344.jpg",
    lat: 46.7917, lng: 17.2333,
    description: "Quality one-storey detached house by the northern shore of the Lake Balaton in Cserszegtomaj is for sale",
  },
  {
    id: "4340",
    title: "Apartment · Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 169444,
    rooms: 3, baths: null, area: 60, plot: null,
    type: "Apartment",
    tag: "City centre",
    agent: "Capital '99 Balaton",
    swatch: "swatch-2",
    photoCount: 12,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "In the midtown of Keszthely 60 sqm flat on the first floor is for sale",
  },
  {
    id: "4339",
    title: "Family house in Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 694444,
    rooms: 7, baths: 5, area: 357, plot: 1700,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 39,
    src: "uploads/scraped-properties/images/family-house-4339.jpg",
    lat: 46.8, lng: 17.3,
    description: "Stunningly located villa near forest by the northern shore of Lake Balaton is for sale",
  },
  {
    id: "4334",
    title: "Family house in Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 411111,
    rooms: 7, baths: 3, area: 182, plot: 946,
    type: "House",
    tag: "Walk to lake",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 34,
    src: null,
    lat: 46.8, lng: 17.3,
    description: "Costantly maintained detached house 800 metres from the Lake Balaton is for sale",
  },
  {
    id: "4332",
    title: "Family house in Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 1100000,
    rooms: 8, baths: 2, area: 170, plot: 990,
    type: "House",
    tag: "Walk to lake",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 32,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Impressive villa in the most valuable street of Keszthely 200 metres from the Lake Balaton is for sale",
  },
  {
    id: "4331",
    title: "Apartment · Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 138611,
    rooms: 2, baths: null, area: 52, plot: null,
    type: "Apartment",
    tag: "Walk to lake",
    agent: "Capital '99 Balaton",
    swatch: "swatch-2",
    photoCount: 31,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Condominium flat on the first floor in Keszthely, 400 metres from the Lake Balaton is for sale",
  },
  {
    id: "4328",
    title: "Family house in Gyenesdiás",
    location: "Gyenesdiás, Balaton",
    region: "Balaton",
    price: 247222,
    rooms: 7, baths: 3, area: 130, plot: 720,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 28,
    src: null,
    lat: 46.779, lng: 17.2806,
    description: "Detached house with 3 apartments in need of refurbishment located in valuable residential area in Gyenesdiás is for sale",
  },
  {
    id: "4327",
    title: "Family house in Balatonszentgyörgy",
    location: "Balatonszentgyörgy, Balaton",
    region: "Balaton",
    price: 399000,
    rooms: 5, baths: 2, area: 180, plot: 1312,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 27,
    src: null,
    lat: 46.6864, lng: 17.3236,
    description: "Constantly maintained detached house in a silent street of Balatonszentgyörgy is for sale",
  },
  {
    id: "4326",
    title: "Holiday home in Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 521000,
    rooms: 4, baths: 2, area: 155, plot: 2763,
    type: "Holiday home",
    tag: "Turnkey",
    agent: "Capital '99 Balaton",
    swatch: "swatch-5",
    photoCount: 26,
    src: "uploads/scraped-properties/images/weekend-house-4326.jpg",
    lat: 46.8, lng: 17.3,
    description: "Modernized holiday home with thached roof only few kms from the nothern shore of Lake Balaton is for sale",
  },
  {
    id: "4322",
    title: "Family house in Vonyarcvashegy",
    location: "Vonyarcvashegy, Balaton",
    region: "Balaton",
    price: 180277,
    rooms: 2, baths: null, area: 50, plot: 200,
    type: "House",
    tag: "Refurbished",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 22,
    src: null,
    lat: 46.7681, lng: 17.3197,
    description: "Constantly tended and professionally refurbished traditional cottage with thached roof near the centre of Vonyarcvashegy, 400 metres from the Lake Balaton in a silent side street is for sale",
  },
  {
    id: "4317",
    title: "Family house in Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 297222,
    rooms: 2, baths: null, area: 51, plot: 250,
    type: "House",
    tag: "Walk to lake",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 17,
    src: null,
    lat: 46.8, lng: 17.3,
    description: "Modern holiday home only few walking minutes from the Lake Balaton is for sale",
  },
  {
    id: "4315",
    title: "Family house in Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 450000,
    rooms: 8, baths: 3, area: 276, plot: 965,
    type: "House",
    tag: "Walk to lake",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 15,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Detached house fit for several generations in Keszthely 800 metres from the Lake Balaton is for sale",
  },
  {
    id: "4314",
    title: "Family house in Zalaapáti",
    location: "Zalaapáti, West Transdanubia",
    region: "West Transdanubia",
    price: 166388,
    rooms: 3, baths: null, area: 70, plot: 2000,
    type: "House",
    tag: "Refurbished",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 14,
    src: null,
    lat: 46.7167, lng: 17.1333,
    description: "Thoroughly refurbished detached house near the centre of Zalaapáti is for sale",
  },
  {
    id: "4311",
    title: "Family house in Marcali",
    location: "Marcali, South Transdanubia",
    region: "South Transdanubia",
    price: 221944,
    rooms: 4, baths: null, area: 110, plot: 1500,
    type: "House",
    tag: "Refurbished",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 39,
    src: null,
    lat: 46.5833, lng: 17.4167,
    description: "Completely refurbished detached house centrally but silently located in Marcali is for sale",
  },
  {
    id: "4307",
    title: "Family house in Cserszegtomaj",
    location: "Cserszegtomaj, Balaton",
    region: "Balaton",
    price: 1052777,
    rooms: 5, baths: 3, area: 261, plot: 1200,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 35,
    src: null,
    lat: 46.7917, lng: 17.2333,
    description: "Modern detached house as new silently located in Cserszegtomaj is for sale",
  },
  {
    id: "4306",
    title: "Family house in Hévíz",
    location: "Hévíz, Balaton",
    region: "Balaton",
    price: 625000,
    rooms: 5, baths: 2, area: 198, plot: 965,
    type: "House",
    tag: "Near thermal spa",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 34,
    src: null,
    lat: 46.7878, lng: 17.1903,
    description: "Quality detached house silently located in spa town Hévíz is for sale",
  },
  {
    id: "4305",
    title: "Holiday home in Gyenesdiás",
    location: "Gyenesdiás, Balaton",
    region: "Balaton",
    price: 180000,
    rooms: 3, baths: 2, area: 58, plot: 1473,
    type: "Holiday home",
    tag: "Turnkey",
    agent: "Capital '99 Balaton",
    swatch: "swatch-5",
    photoCount: 33,
    src: null,
    lat: 46.779, lng: 17.2806,
    description: "Silently located holiday cottage near forest in Gyenesdiás is for sale",
  },
  {
    id: "4303",
    title: "New-build house · Balatongyörök",
    location: "Balatongyörök, Balaton",
    region: "Balaton",
    price: 525000,
    rooms: 4, baths: 2, area: 120, plot: 1000,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 31,
    src: "uploads/scraped-properties/images/family-house-4303.jpg",
    lat: 46.7497, lng: 17.3556,
    description: "Newly built, energy efficient one-storey detached house in Balatongyörök is for sale",
  },
  {
    id: "4300",
    title: "Family house in Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 500000,
    rooms: 4, baths: 2, area: 165, plot: 1519,
    type: "House",
    tag: "Panoramic view",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 28,
    src: null,
    lat: 46.8, lng: 17.3,
    description: "Silently located detached house with panoramic view of the Lake Balaton just few walking minutes from the lake is for sale",
  },
  {
    id: "4297",
    title: "Family house in Balatonszentgyörgy",
    location: "Balatonszentgyörgy, Balaton",
    region: "Balaton",
    price: 540000,
    rooms: 5, baths: 3, area: 164, plot: 1265,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 25,
    src: null,
    lat: 46.6864, lng: 17.3236,
    description: "Carefully tended detached house near the beach on the Lake Balaton in Balatonszentgyörgy is for sale",
  },
  {
    id: "4295",
    title: "Commercial property · Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 141666,
    rooms: 2, baths: null, area: null, plot: null,
    type: "Commercial",
    tag: "City centre",
    agent: "Capital '99 Balaton",
    swatch: "swatch-8",
    photoCount: 23,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "For residential purposes also useable office in the centre of Keszthely is for sale",
  },
  {
    id: "4291",
    title: "Family house in Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 413888,
    rooms: 9, baths: 6, area: 286, plot: 1029,
    type: "House",
    tag: "City centre",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 19,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Detached house in Bauhaus-style in one of the most valuable parts of Keszthely is for sale",
  },
  {
    id: "4288",
    title: "Guesthouse · Hévíz",
    location: "Hévíz, Balaton",
    region: "Balaton",
    price: 995000,
    rooms: null, baths: 11, area: 650, plot: null,
    type: "Guesthouse",
    tag: "Near thermal spa",
    agent: "Capital '99 Balaton",
    swatch: "swatch-7",
    photoCount: 16,
    src: "uploads/scraped-properties/images/hotel-4288.jpg",
    lat: 46.7878, lng: 17.1903,
    description: "Guesthouse as new centrally located in the spa town of Hévíz is for sale",
  },
  {
    id: "4287",
    title: "Family house in Hévíz",
    location: "Hévíz, Balaton",
    region: "Balaton",
    price: 377777,
    rooms: 7, baths: 3, area: 175, plot: 15,
    type: "House",
    tag: "Spa town",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 15,
    src: null,
    lat: 46.7878, lng: 17.1903,
    description: "Tended terraced house centrally located in Hévíz is for sale",
  },
  {
    id: "4278",
    title: "New-build house · Gyenesdiás",
    location: "Gyenesdiás, Balaton",
    region: "Balaton",
    price: 1097222,
    rooms: 4, baths: 2, area: 196, plot: 1000,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 34,
    src: null,
    lat: 46.779, lng: 17.2806,
    description: "Detached house under construction with panoramic view of the Lake Balaton in a calm, silent side street in Gyenesdiás is for sale",
  },
  {
    id: "4274",
    title: "New-build house · Cserszegtomaj",
    location: "Cserszegtomaj, Balaton",
    region: "Balaton",
    price: 500000,
    rooms: 4, baths: 3, area: 201, plot: 1519,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 30,
    src: null,
    lat: 46.7917, lng: 17.2333,
    description: "Newly built detached house in Cserszegtomaj, in a calm side street is for sale",
  },
  {
    id: "4270",
    title: "Family house in Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 413888,
    rooms: 6, baths: 2, area: 197, plot: 1007,
    type: "House",
    tag: "Walk to lake",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 26,
    src: null,
    lat: 46.8, lng: 17.3,
    description: "Modern detached house under construction 500 metres from the Lake Balaton is for sale",
  },
  {
    id: "4268",
    title: "Family house in Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 719444,
    rooms: 4, baths: 2, area: 247, plot: 1349,
    type: "House",
    tag: "Walk to lake",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 24,
    src: null,
    lat: 46.8, lng: 17.3,
    description: "Modern detached house under construction 500 metres from the Lake Balaton is for sale",
  },
  {
    id: "4263",
    title: "Family house in Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 265000,
    rooms: 8, baths: 3, area: 255, plot: 5157,
    type: "House",
    tag: "Refurbished",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 19,
    src: null,
    lat: 46.8, lng: 17.3,
    description: "Refurbished manor house near the thermal baths is for sale",
  },
  {
    id: "4262",
    title: "Building plot · Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 272222,
    rooms: null, baths: null, area: null, plot: 1971,
    type: "Plot",
    tag: "Panoramic view",
    agent: "Capital '99 Balaton",
    swatch: "swatch-6",
    photoCount: 18,
    src: null,
    lat: 46.8, lng: 17.3,
    description: "Construction lot with panoramic view of the lake north of the Lake Balaton is for sale",
  },
  {
    id: "4261",
    title: "New-build house · Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 552777,
    rooms: 3, baths: null, area: 192, plot: 1678,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 17,
    src: null,
    lat: 46.8, lng: 17.3,
    description: "Newly built detached house in stunning natural location north from the Lake Balaton is for sale",
  },
  {
    id: "4259",
    title: "New-build house · Gyenesdiás",
    location: "Gyenesdiás, Balaton",
    region: "Balaton",
    price: 611111,
    rooms: 4, baths: 2, area: 150, plot: 945,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 15,
    src: "uploads/scraped-properties/images/family-house-4259.jpg",
    lat: 46.779, lng: 17.2806,
    description: "Newly built one-storey detached house in the settlement of Gyenesdiás on the northern shore of the Lake Balaton in silent location is for sale",
  },
  {
    id: "4255",
    title: "Building plot · Hévíz",
    location: "Hévíz, Balaton",
    region: "Balaton",
    price: 55277,
    rooms: null, baths: null, area: null, plot: 980,
    type: "Plot",
    tag: "Near thermal spa",
    agent: "Capital '99 Balaton",
    swatch: "swatch-6",
    photoCount: 39,
    src: null,
    lat: 46.7878, lng: 17.1903,
    description: "Construction lot in excellent location in the vicinity of spa town Hévíz is for sale",
  },
  {
    id: "4254",
    title: "Building plot · Hévíz",
    location: "Hévíz, Balaton",
    region: "Balaton",
    price: 52500,
    rooms: null, baths: null, area: null, plot: 800,
    type: "Plot",
    tag: "Near thermal spa",
    agent: "Capital '99 Balaton",
    swatch: "swatch-6",
    photoCount: 38,
    src: null,
    lat: 46.7878, lng: 17.1903,
    description: "Construction lot in excellent location in the vicinity of spa town Hévíz is for sale",
  },
  {
    id: "4247",
    title: "Family house in Hévíz",
    location: "Hévíz, Balaton",
    region: "Balaton",
    price: 500000,
    rooms: 5, baths: null, area: 151, plot: 1172,
    type: "House",
    tag: "Spa town",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 31,
    src: null,
    lat: 46.7878, lng: 17.1903,
    description: "Detached house in excellent condition 3 kms from Hévíz is for sale",
  },
  {
    id: "4246",
    title: "Building plot · Cserszegtomaj",
    location: "Cserszegtomaj, Balaton",
    region: "Balaton",
    price: 69166,
    rooms: null, baths: null, area: null, plot: 2001,
    type: "Plot",
    tag: "Building land",
    agent: "Capital '99 Balaton",
    swatch: "swatch-6",
    photoCount: 30,
    src: null,
    lat: 46.7917, lng: 17.2333,
    description: "Construction lot in calm residential area in Cserszegtomaj is for sale",
  },
  {
    id: "4243",
    title: "Family house in Sümeg",
    location: "Sümeg, West Transdanubia",
    region: "West Transdanubia",
    price: 430000,
    rooms: 4, baths: 3, area: 165, plot: 3375,
    type: "House",
    tag: "Refurbished",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 27,
    src: null,
    lat: 47, lng: 17.2833,
    description: "Professionally and qualitatively refurbished real estate complex 5 kms from Sümeg is for sale",
  },
  {
    id: "4236",
    title: "Family house in Somogy",
    location: "Somogy, South Transdanubia",
    region: "South Transdanubia",
    price: 650000,
    rooms: 9, baths: 3, area: 282, plot: 3000,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 20,
    src: null,
    lat: 46.6, lng: 17.5,
    description: "Constantly maintained detached house at the boundary of the counties of Somogy and Zala, in an enchanting village is for sale",
  },
  {
    id: "4230",
    title: "Family house in Vörs",
    location: "Vörs, Balaton",
    region: "Balaton",
    price: 250000,
    rooms: 4, baths: 3, area: 154, plot: 3805,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 14,
    src: null,
    lat: 46.65, lng: 17.3,
    description: "Well maintained detached house with guest house in Vörs, 5 kms from the Lake Balaton is for sale",
  },
  {
    id: "4226",
    title: "Family house in Gyenesdiás",
    location: "Gyenesdiás, Balaton",
    region: "Balaton",
    price: 688888,
    rooms: 8, baths: 5, area: 300, plot: 1265,
    type: "House",
    tag: "Walk to lake",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 38,
    src: null,
    lat: 46.779, lng: 17.2806,
    description: "Elegant quality detached house in Gyenesdiás, 500 metres from the Lake Balaton is for sale",
  },
  {
    id: "4223",
    title: "Family house in Cserszegtomaj",
    location: "Cserszegtomaj, Balaton",
    region: "Balaton",
    price: 745000,
    rooms: 10, baths: 7, area: 384, plot: 4124,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 35,
    src: null,
    lat: 46.7917, lng: 17.2333,
    description: "Constantly maintained, elegant detached house in Cserszegtomaj, in stunning natural location is for sale",
  },
  {
    id: "4217",
    title: "New-build house · Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 235833,
    rooms: 2, baths: null, area: 50, plot: null,
    type: "Apartment",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-2",
    photoCount: 29,
    src: "uploads/scraped-properties/images/flat-4217.jpg",
    lat: 46.7686, lng: 17.2444,
    description: "Newly built apartment in Keszthely, 200 metres from the Lake Balaton in a modern building is for sale",
  },
  {
    id: "4216",
    title: "New-build house · Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 277500,
    rooms: 2, baths: null, area: 58, plot: null,
    type: "Apartment",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-2",
    photoCount: 28,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Newly built apartment with own garden area in Keszthely, 200 metres from the Lake Balaton in a modern building is for sale",
  },
  {
    id: "4215",
    title: "New-build house · Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 277500,
    rooms: 2, baths: null, area: 58, plot: null,
    type: "Apartment",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-2",
    photoCount: 27,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Newly built apartment with own garden area in Keszthely, 200 metres from the Lake Balaton in a modern building is for sale",
  },
  {
    id: "4190",
    title: "New-build house · Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 1041666,
    rooms: 4, baths: 2, area: 162, plot: 2040,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 30,
    src: null,
    lat: 46.8, lng: 17.3,
    description: "Newly built, very high-quality one storey detached house 1 km from the Lake Balaton on the northern coast is for sale",
  },
  {
    id: "4187",
    title: "Apartment · Hévíz",
    location: "Hévíz, Balaton",
    region: "Balaton",
    price: 247222,
    rooms: 4, baths: 2, area: 130, plot: 600,
    type: "Apartment",
    tag: "Near thermal spa",
    agent: "Capital '99 Balaton",
    swatch: "swatch-2",
    photoCount: 27,
    src: null,
    lat: 46.7878, lng: 17.1903,
    description: "First floor apartment in a detached house situated in one of the nicest streets in the spa town of Hévíz is for sale",
  },
  {
    id: "4182",
    title: "Building plot · Cserszegtomaj",
    location: "Cserszegtomaj, Balaton",
    region: "Balaton",
    price: 180277,
    rooms: null, baths: null, area: null, plot: 1500,
    type: "Plot",
    tag: "Panoramic view",
    agent: "Capital '99 Balaton",
    swatch: "swatch-6",
    photoCount: 22,
    src: null,
    lat: 46.7917, lng: 17.2333,
    description: "Silently located construction lot in Cserszegtomaj with panoramic view of the Lake Balaton is for sale",
  },
  {
    id: "4181",
    title: "Family house in Cserszegtomaj",
    location: "Cserszegtomaj, Balaton",
    region: "Balaton",
    price: 650000,
    rooms: 4, baths: 2, area: 198, plot: 1500,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 21,
    src: null,
    lat: 46.7917, lng: 17.2333,
    description: "One-storey detached house as new centrally located in Cserszegtomaj is for sale",
  },
  {
    id: "4177",
    title: "New-build house · Cserszegtomaj",
    location: "Cserszegtomaj, Balaton",
    region: "Balaton",
    price: 1100000,
    rooms: 5, baths: 2, area: 200, plot: 1656,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 17,
    src: null,
    lat: 46.7917, lng: 17.2333,
    description: "Modern detached house as new, silently located in Cserszegtomaj is for sale",
  },
  {
    id: "4166",
    title: "Family house in Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 315000,
    rooms: 4, baths: null, area: 130, plot: 735,
    type: "House",
    tag: "Walk to lake",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 34,
    src: null,
    lat: 46.8, lng: 17.3,
    description: "Constantly maintained detached house 600 metres from the Lake Balaton is for sale",
  },
  {
    id: "4159",
    title: "New-build house · Cserszegtomaj",
    location: "Cserszegtomaj, Balaton",
    region: "Balaton",
    price: 602777,
    rooms: 5, baths: 3, area: 159, plot: 1240,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 27,
    src: null,
    lat: 46.7917, lng: 17.2333,
    description: "Newly built detached house in Cserszegtomaj, in very calm location is for sale",
  },
  {
    id: "4158",
    title: "New-build house · Cserszegtomaj",
    location: "Cserszegtomaj, Balaton",
    region: "Balaton",
    price: 663888,
    rooms: 5, baths: 3, area: 165, plot: 1240,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 26,
    src: null,
    lat: 46.7917, lng: 17.2333,
    description: "Newly built detached house in Cserszegtomaj, in very calm location is for sale",
  },
  {
    id: "4145",
    title: "Family house in Hévíz",
    location: "Hévíz, Balaton",
    region: "Balaton",
    price: 444166,
    rooms: 4, baths: 2, area: 161, plot: 1473,
    type: "House",
    tag: "Near thermal spa",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 13,
    src: null,
    lat: 46.7878, lng: 17.1903,
    description: "Newly built one-storey detached house in Cserszegtomaj, in silent location, only few kms from the spa town of Hévíz is for sale",
  },
  {
    id: "4135",
    title: "Family house in Hévíz",
    location: "Hévíz, Balaton",
    region: "Balaton",
    price: 416388,
    rooms: 7, baths: 4, area: 181, plot: 614,
    type: "House",
    tag: "Spa town",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 31,
    src: null,
    lat: 46.7878, lng: 17.1903,
    description: "Detached house made of two living units, centrally located in Hévíz is for sale",
  },
  {
    id: "4125",
    title: "New-build house · Gyenesdiás",
    location: "Gyenesdiás, Balaton",
    region: "Balaton",
    price: 1300000,
    rooms: 5, baths: 3, area: 190, plot: 1417,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 9,
    src: "uploads/scraped-properties/images/detail-4125-interior1.jpg",
    lat: 46.779, lng: 17.2806,
    description: "Newly built detached house in Gyenesdiás, located in gorgeous nature is for sale",
  },
  {
    id: "4121",
    title: "Family house in Balatonberény",
    location: "Balatonberény, Balaton",
    region: "Balaton",
    price: 415277,
    rooms: 6, baths: 2, area: 136, plot: 787,
    type: "House",
    tag: "Walk to lake",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 17,
    src: null,
    lat: 46.705, lng: 17.3,
    description: "Stunning quality home by the southern shore of Lake Balaton, in Balatonberény, 800 metres from the Lake is for sale",
  },
  {
    id: "4120",
    title: "Family house in Balatongyörök",
    location: "Balatongyörök, Balaton",
    region: "Balaton",
    price: 299000,
    rooms: 6, baths: 3, area: 170, plot: 1780,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 16,
    src: null,
    lat: 46.7497, lng: 17.3556,
    description: "Constantly tended detached house in good condition in Balatongyörök is for sale",
  },
  {
    id: "4114",
    title: "New-build house · Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 1050000,
    rooms: 5, baths: 2, area: 214, plot: 1660,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 38,
    src: "uploads/scraped-properties/images/family-house-4114.jpg",
    lat: 46.8, lng: 17.3,
    description: "Nicely located newly built detached house by the northern shore of Lake Balaton",
  },
  {
    id: "4112",
    title: "New-build house · Vonyarcvashegy",
    location: "Vonyarcvashegy, Balaton",
    region: "Balaton",
    price: 347222,
    rooms: 3, baths: 2, area: 72, plot: 350,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 36,
    src: null,
    lat: 46.7681, lng: 17.3197,
    description: "Newly built one-storey detached house in Vonyarcvashegy, in a modern residential complex is for sale",
  },
  {
    id: "4109",
    title: "New-build house · Cserszegtomaj",
    location: "Cserszegtomaj, Balaton",
    region: "Balaton",
    price: 444166,
    rooms: 4, baths: 2, area: 170, plot: 1386,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 33,
    src: null,
    lat: 46.7917, lng: 17.2333,
    description: "Newly built one-storey detached house in Cserszegtomaj, in calm, silent location is for sale",
  },
  {
    id: "4096",
    title: "New-build house · Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 541666,
    rooms: 4, baths: 2, area: 120, plot: 740,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 20,
    src: "uploads/scraped-properties/images/family-house-4096.jpg",
    lat: 46.7686, lng: 17.2444,
    description: "Newly built detached house directly next to forest in a silent, calm location in the vicinity of Hévíz and Keszthely is for sale",
  },
  {
    id: "4074",
    title: "Apartment · Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 213611,
    rooms: 3, baths: null, area: 61, plot: 50,
    type: "Apartment",
    tag: "Walk to lake",
    agent: "Capital '99 Balaton",
    swatch: "swatch-2",
    photoCount: 26,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Apartment as new on the first floor of a 3-unit condominium in Keszthely, 400 metres from the Lake Balaton is for sale",
  },
  {
    id: "4055",
    title: "Building plot · Cserszegtomaj",
    location: "Cserszegtomaj, Balaton",
    region: "Balaton",
    price: 66666,
    rooms: null, baths: null, area: null, plot: 3259,
    type: "Plot",
    tag: "Building land",
    agent: "Capital '99 Balaton",
    swatch: "swatch-6",
    photoCount: 35,
    src: null,
    lat: 46.7917, lng: 17.2333,
    description: "Construction lot in Cserszegtomaj, in an area near the centre of the settlement is for sale",
  },
  {
    id: "4053",
    title: "Apartment · Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 291666,
    rooms: 4, baths: null, area: 91, plot: 120,
    type: "Apartment",
    tag: "City centre",
    agent: "Capital '99 Balaton",
    swatch: "swatch-2",
    photoCount: 33,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Very carefully tended terraced house in a residential complex situated in a wonderful natural location near Keszthely—Hévíz",
  },
  {
    id: "4036",
    title: "Family house in Zala",
    location: "Zala, West Transdanubia",
    region: "West Transdanubia",
    price: 370000,
    rooms: 5, baths: 2, area: 192, plot: 800,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 16,
    src: null,
    lat: 46.7833, lng: 16.95,
    description: "Newly built one-storeyed detached house in Zalakaros, in a very calm surrounding is for sale",
  },
  {
    id: "4033",
    title: "New-build house · Balatongyörök",
    location: "Balatongyörök, Balaton",
    region: "Balaton",
    price: 494444,
    rooms: 3, baths: null, area: 90, plot: 1000,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 13,
    src: null,
    lat: 46.7497, lng: 17.3556,
    description: "Newly built detached house in a calm, silent part of Balatongyörök is for sale",
  },
  {
    id: "4027",
    title: "Family house in Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 527777,
    rooms: 8, baths: 2, area: 260, plot: 688,
    type: "House",
    tag: "Refurbished",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 35,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Completely refurbished villa in the town centre of Keszthely, 500 metres from the Lake Balaton is for sale",
  },
  {
    id: "4017",
    title: "Family house in Hévíz",
    location: "Hévíz, Balaton",
    region: "Balaton",
    price: 444444,
    rooms: 7, baths: 5, area: 250, plot: 686,
    type: "House",
    tag: "Near thermal spa",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 25,
    src: null,
    lat: 46.7878, lng: 17.1903,
    description: "Constantly maintained, silently located detached house in the spa town of Hévíz",
  },
  {
    id: "4003",
    title: "Family house in Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 246944,
    rooms: 6, baths: 2, area: 155, plot: 696,
    type: "House",
    tag: "City centre",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 39,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Detached house in a silent, calm street without transit traffic favourably located in Keszthely is for sale",
  },
  {
    id: "3972",
    title: "Family house in Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 522222,
    rooms: 7, baths: 2, area: 177, plot: 1015,
    type: "House",
    tag: "City centre",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 36,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Constantly maintained, in 2020 remodelled detached house in very good condition in Cserszegtomaj, near Hévíz and Keszthely is for sale",
  },
  {
    id: "3948",
    title: "Family house in Hévíz",
    location: "Hévíz, Balaton",
    region: "Balaton",
    price: 1375000,
    rooms: 12, baths: 10, area: 600, plot: 1022,
    type: "House",
    tag: "Near thermal spa",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 12,
    src: null,
    lat: 46.7878, lng: 17.1903,
    description: "Family pension in Hévíz, 5-10 walking minutes from the centre of the spa town is for sale",
  },
  {
    id: "3947",
    title: "Family house in Cserszegtomaj",
    location: "Cserszegtomaj, Balaton",
    region: "Balaton",
    price: 390000,
    rooms: 6, baths: 2, area: 159, plot: 533,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 39,
    src: null,
    lat: 46.7917, lng: 17.2333,
    description: "Quality detached house in Cserszegtomaj in green setting is for sale",
  },
  {
    id: "3934",
    title: "Family house in Vonyarcvashegy",
    location: "Vonyarcvashegy, Balaton",
    region: "Balaton",
    price: 386111,
    rooms: 5, baths: 2, area: 120, plot: 367,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 26,
    src: null,
    lat: 46.7681, lng: 17.3197,
    description: "Silently located detached house in Mediterranean style in a calm side street in Vonyarcvashegy, only 10 walking minutes to the Lake Balaton",
  },
  {
    id: "3931",
    title: "Building plot · Hévíz",
    location: "Hévíz, Balaton",
    region: "Balaton",
    price: 150000,
    rooms: null, baths: null, area: null, plot: 1441,
    type: "Plot",
    tag: "Near thermal spa",
    agent: "Capital '99 Balaton",
    swatch: "swatch-6",
    photoCount: 23,
    src: null,
    lat: 46.7878, lng: 17.1903,
    description: "Nice, square-shaped building lot in the northern part of the spa town of Hévíz, in Egregy is for sale",
  },
  {
    id: "3923",
    title: "New-build house · Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 347222,
    rooms: 4, baths: 2, area: 86, plot: 350,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 15,
    src: null,
    lat: 46.8, lng: 17.3,
    description: "Newly built detached houses in a housing complex lying near the forest by the Lake Balaton",
  },
  {
    id: "3921",
    title: "New-build house · Gyenesdiás",
    location: "Gyenesdiás, Balaton",
    region: "Balaton",
    price: 694444,
    rooms: 6, baths: 5, area: 195, plot: 1063,
    type: "House",
    tag: "New build",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 13,
    src: null,
    lat: 46.779, lng: 17.2806,
    description: "Apartment house newly built in high quality in Gyenesdiás, 1 km from the beach away",
  },
  {
    id: "3898",
    title: "Family house in Hévíz",
    location: "Hévíz, Balaton",
    region: "Balaton",
    price: 375000,
    rooms: 9, baths: 7, area: 340, plot: 950,
    type: "House",
    tag: "Near thermal spa",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 18,
    src: null,
    lat: 46.7878, lng: 17.1903,
    description: "Silently located detached house in Hévíz, 1 km from the thermal lake",
  },
  {
    id: "3890",
    title: "Family house in Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 1200000,
    rooms: 4, baths: 2, area: 160, plot: 617,
    type: "House",
    tag: "Refurbished",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 38,
    src: "uploads/scraped-properties/images/family-house-3890.jpg",
    lat: 46.7686, lng: 17.2444,
    description: "Detached house very carefully refurbished in high-quatity located in Keszthely near the town centre and the Balaton",
  },
  {
    id: "3885",
    title: "Family house in Keszthely",
    location: "Keszthely, Balaton",
    region: "Balaton",
    price: 819444,
    rooms: 11, baths: 11, area: 480, plot: 551,
    type: "House",
    tag: "Walk to lake",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 33,
    src: null,
    lat: 46.7686, lng: 17.2444,
    description: "Successfully operated, constantly maintained pension in Keszthely, 400 metres from the Lake Balaton",
  },
  {
    id: "3881",
    title: "Family house in Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 772222,
    rooms: 15, baths: 6, area: 295, plot: 1000,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 29,
    src: null,
    lat: 46.8, lng: 17.3,
    description: "Constantly maintained detached house comprising 6 separate dwelling units, apartments",
  },
  {
    id: "3832",
    title: "Family house in Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 990000,
    rooms: 5, baths: 3, area: 274, plot: 1033,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 36,
    src: "uploads/scraped-properties/images/family-house-3832.jpg",
    lat: 46.8, lng: 17.3,
  },
  {
    id: "3653",
    title: "Family house in Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 550000,
    rooms: 11, baths: 6, area: 264, plot: 838,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 25,
    src: null,
    lat: 46.8, lng: 17.3,
  },
  {
    id: "3244",
    title: "Family house in Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 600000,
    rooms: null, baths: null, area: null, plot: 2961,
    type: "House",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-1",
    photoCount: 36,
    src: null,
    lat: 46.8, lng: 17.3,
  },
  {
    id: "3223",
    title: "Guesthouse · Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 3600000,
    rooms: 30, baths: 30, area: 1145, plot: null,
    type: "Guesthouse",
    tag: "Featured",
    agent: "Capital '99 Balaton",
    swatch: "swatch-7",
    photoCount: 15,
    src: "uploads/scraped-properties/images/hotel-3223.jpg",
    lat: 46.8, lng: 17.3,
  },
  {
    id: "2933",
    title: "Building plot · Balaton region",
    location: "Balaton region, Balaton",
    region: "Balaton",
    price: 1097222,
    rooms: null, baths: null, area: null, plot: 15814,
    type: "Plot",
    tag: "Building land",
    agent: "Capital '99 Balaton",
    swatch: "swatch-6",
    photoCount: 33,
    src: null,
    lat: 46.8, lng: 17.3,
  }
];

const REGIONS = [
  { id: "balaton", name: "Balaton", count: 108, blurb: "Lake & wine country", swatch: "swatch-1" },
  { id: "budapest", name: "Budapest", count: 1284, blurb: "Capital & inner districts", swatch: "swatch-2" },
  { id: "danube", name: "Danube Bend", count: 187, blurb: "Cliffs north of the capital", swatch: "swatch-4" },
  { id: "puszta", name: "Great Plain", count: 96, blurb: "Puszta, horse country", swatch: "swatch-3" },
  { id: "west", name: "West Transdanubia", count: 4, blurb: "Sopron, Győr, Austria edge", swatch: "swatch-8" },
  { id: "south", name: "South Transdanubia", count: 2, blurb: "Pécs, Mecsek hills", swatch: "swatch-7" }
];

const TYPES = ["Any type", "House", "Apartment", "Villa", "Holiday home", "Plot", "Farmhouse", "Guesthouse", "Commercial"];
const ROOMS = ["Any", "1+", "2+", "3+", "4+", "5+"];
const PRICES = ["Any price", "Up to €50k", "€50k – €100k", "€100k – €200k", "€200k – €350k", "€350k – €500k", "€500k+"];

const SUGGESTIONS = [
  { kind: "Region", label: "Balaton", hint: "108 listings" },
  { kind: "Region", label: "West Transdanubia", hint: "4 listings" },
  { kind: "Region", label: "South Transdanubia", hint: "2 listings" },
  { kind: "City", label: "Keszthely", hint: "29 listings" },
  { kind: "City", label: "Balaton region", hint: "24 listings" },
  { kind: "City", label: "Hévíz", hint: "17 listings" },
  { kind: "City", label: "Cserszegtomaj", hint: "17 listings" },
  { kind: "City", label: "Gyenesdiás", hint: "7 listings" },
  { kind: "City", label: "Vonyarcvashegy", hint: "6 listings" },
  { kind: "City", label: "Balatonszentgyörgy", hint: "3 listings" },
  { kind: "City", label: "Balatongyörök", hint: "3 listings" }
];

// Format a € price with thousands separator
function fmtPrice(n) {
  if (n == null) return "—";
  return "€" + n.toLocaleString("en-US");
}

Object.assign(window, { PROPERTIES, REGIONS, TYPES, ROOMS, PRICES, SUGGESTIONS, fmtPrice });
